name: mkdocs
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:
      - master
    paths:
      - "docs/*.md"
      - ".github/workflows/mkdocs.yml"
      - "mkdocs.yml"
      - "requirements.txt"
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: mkdocs build
        run: mkdocs build
      - name: mkdocs gh-deploy
        run: mkdocs gh-deploy
